global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ground_station'
    static_configs:
      - targets: ['host.docker.internal:9091']
    
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']